CREATE TABLE IF NOT EXISTS budget (id INTEGER PRIMARY KEY CHECK(id=1), reserved_fen INTEGER NOT NULL, flyai INTEGER NOT NULL, bailian INTEGER NOT NULL, amap INTEGER NOT NULL);
-- Seeded from the existing local ledger before launch. Never reset on deploy.
INSERT OR IGNORE INTO budget VALUES (1,9500,64,21,10);
CREATE TABLE IF NOT EXISTS comparisons (id TEXT PRIMARY KEY, value TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS leases (id TEXT PRIMARY KEY, token TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS requests (id TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
