'use client';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { nextSaturday } from '../src/model';
import type { Place, LocalTrip } from '../src/local-model';
import type { compareLocal } from '../src/local-service';
type Person={name:string;query:string;place:Place|null;maxMinutes:number;mode:'transit'|'walking'|'driving'};
type Result=Awaited<ReturnType<typeof compareLocal>>;
const modes={transit:'地铁 / 公交',walking:'步行',driving:'驾车'};
async function request<T>(body:unknown):Promise<T>{const r=await fetch('/api/local',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(180_000)});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
export default function LocalPlanner(){
 const feedback=useRef<HTMLDivElement>(null);
 const [city,setCity]=useState('上海'); const [date,setDate]=useState(nextSaturday);const [time,setTime]=useState('13:00');
 const [members,setMembers]=useState<Person[]>([{name:'我',query:'徐家汇地铁站',place:null,maxMinutes:60,mode:'transit'},{name:'朋友 A',query:'五角场地铁站',place:null,maxMinutes:60,mode:'transit'}]);
 const [kind,setKind]=useState('咖啡厅');const [candidateQuery,setCandidateQuery]=useState('');const [candidates,setCandidates]=useState<Place[]>([]);
 const [choices,setChoices]=useState<{target:number;places:Place[]}|null>(null); const [busy,setBusy]=useState('');const [error,setError]=useState('');const [result,setResult]=useState<Result|null>(null);const [configured,setConfigured]=useState<boolean|null>(null);const [mapNotice,setMapNotice]=useState('地图服务尚未接通，请稍后再试。');
 useEffect(()=>{fetch('/api/status').then(r=>r.json()).then(r=>{setConfigured(r.map===true);if(r.mapNotice)setMapNotice(r.mapNotice);}).catch(()=>{});},[]);
 useEffect(()=>{if(error)feedback.current?.scrollIntoView({behavior:'smooth',block:'center'});},[error]);
 function clear(){setResult(null);setError('');setChoices(null);}
 function update(index:number,patch:Partial<Person>){clear();setMembers(old=>old.map((m,i)=>i===index?{...m,...patch}:m));}
 async function run(task:string,action:()=>Promise<void>){setBusy(task);setError('');try{await action();}catch(e){setError((e as Error).name==='TimeoutError'?'地图查询超时，请稍后重试。':(e as Error).message);}finally{setBusy('');}}
 async function search(target:number){await run('search',async()=>{const data=await request<{places:Place[]}>({action:'search',city,keywords:target<0?candidateQuery:members[target].query});setChoices({target,places:data.places});if(!data.places.length)setError('没有找到匹配地点，请补充地铁站名、商场名或街道。');});}
 async function suggest(){clear();await run('suggest',async()=>{if(members.some(m=>!m.place))throw new Error('请先搜索并确认每个人的出发地点。');const data=await request<{places:Place[]}>({action:'suggest',city,origins:members.map(m=>m.place),kind});setCandidates(data.places);if(!data.places.length)throw new Error('附近没有返回候选地点，请手动添加想比较的地方。');});}
 async function compare(){clear();await run('compare',async()=>{if(members.some(m=>!m.place))throw new Error('请先搜索并确认每个人的出发地点。');if(!candidates.length)throw new Error('请先寻找候选地点，或手动添加想比较的地方。');const trip:LocalTrip={city,date,time,members:members.map(m=>({name:m.name,place:m.place!,maxMinutes:m.maxMinutes,mode:m.mode})),candidates};setResult(await request<Result>({action:'compare',trip}));});}
 function placeChoices(target:number){return choices&&choices.target===target&&choices.places.length>0&&<div className="place-choices" aria-label="地点搜索结果"><strong>确认{choices.target<0?'候选地点':members[choices.target].name+'的出发点'}</strong>{choices.places.map(p=><button type="button" key={p.id} onClick={()=>{const target=choices.target;clear();if(target<0)setCandidates(old=>old.some(c=>c.id===p.id)?old:[...old,p].slice(0,3));else setMembers(old=>old.map((m,i)=>i===target?{...m,place:p,query:p.name}:m));}}><b>{p.name}</b><span>{p.address} · {p.city}</span></button>)}</div>;}
 return <section className="local-planner" id="planner" aria-label="同城见面计划">
 <div className="workspace-bar"><div className="workspace-title">一座城市，也值得公平相聚</div><span className="small muted">按各自出行方式比较单程用时</span></div>
 <div className="local-workspace"><div className="local-form">
 <fieldset disabled={!!busy||configured===false}><legend className="sr-only">同城见面条件</legend>
 <div className="local-date"><label>在哪座城市<input list="city-suggestions" aria-label="同城城市" value={city} onChange={e=>{clear();setCity(e.target.value);setCandidates([]);setMembers(members.map(m=>({...m,place:null})));}}/></label><label>出发日期<input type="date" value={date} onChange={e=>{clear();setDate(e.target.value);}}/></label><label>大约几点出发<input type="time" value={time} onChange={e=>{clear();setTime(e.target.value);}}/></label></div>
 <h3 className="local-label">大家从哪里来 <span>{members.length}/4</span></h3>
 <p className="small muted">选附近的地铁站或公共地标就好。输入后，搜索并确认具体地点。</p>
 {members.map((m,i)=><div className="local-member" key={i}><div className="local-member-top"><span className="person" style={{backgroundPosition:`${i*100/3}% center`}}/><input className="local-name" aria-label={`同城成员${i+1}称呼`} value={m.name} maxLength={16} onChange={e=>update(i,{name:e.target.value})}/>{members.length>2&&<button type="button" className="text-button" onClick={()=>{clear();setMembers(members.filter((_,j)=>j!==i));}}>移除</button>}</div><div className="place-search"><input aria-label={`${m.name}出发地点`} value={m.query} placeholder="地铁站、商场或公共地标" maxLength={80} onChange={e=>update(i,{query:e.target.value,place:null})}/><button type="button" className="outline-button" onClick={()=>search(i)} disabled={m.query.trim().length<2}>搜索地点</button></div>{m.place&&<p className="confirmed-place">✓ {m.place.name}<span>{m.place.address}</span></p>}{placeChoices(i)}<div className="local-controls"><label>怎么去<select aria-label={`${m.name}出行方式`} value={m.mode} onChange={e=>update(i,{mode:e.target.value as Person['mode']})}>{Object.entries(modes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>单程最多<div className="input-unit"><input type="number" aria-label={`${m.name}单程上限`} min={5} max={240} value={m.maxMinutes} onChange={e=>update(i,{maxMinutes:Number(e.target.value)})}/><span>分钟</span></div></label></div></div>)}
 {members.length<4&&<button type="button" className="add-member" onClick={()=>{clear();setMembers([...members,{name:`朋友 ${members.length}`,query:'',place:null,maxMinutes:60,mode:'transit'}]);}}>＋ 添加见面的人</button>}
 <h3 className="local-label">想在哪里见</h3><div className="place-search"><select aria-label="相聚场所类型" value={kind} onChange={e=>{clear();setKind(e.target.value);setCandidates([]);}}><option>咖啡厅</option><option>餐厅</option><option>公园</option></select><button type="button" className="outline-button" onClick={suggest}>寻找候选地点</button></div><p className="small muted">先在大家的地理中点附近找候选，再用真实路线比较；也可以自行添加。</p>
 <div className="place-search"><input aria-label="添加同城候选地点" placeholder="或输入你想比较的地点" value={candidateQuery} onChange={e=>setCandidateQuery(e.target.value)} maxLength={80}/><button className="outline-button" type="button" disabled={candidates.length>=3||candidateQuery.trim().length<2} onClick={()=>search(-1)}>搜索添加</button></div>
 <div className="local-candidates">{candidates.map(p=><div key={p.id}><strong>{p.name}</strong><span>{p.address}</span><button type="button" aria-label={`移除${p.name}`} onClick={()=>{clear();setCandidates(candidates.filter(c=>c.id!==p.id));}}>×</button></div>)}</div>
 {placeChoices(-1)}
 </fieldset></div>
 <aside className="local-aside"><Image src="/art/together.webp" alt="围坐一桌的相聚插画" width={480} height={480} sizes="(max-width:760px) 220px, 340px"/><h3>不必跨城，<br/>也能少一点迁就。</h3><p>住在城市两端，也能找到<br/>大家都方便抵达的地方。</p>{configured===false&&<div className="map-pending" role="status"><strong>同城查询暂未开放</strong><p>{mapNotice}</p></div>}<button type="button" className="button search-button" disabled={!!busy||configured===false} onClick={compare}>{busy?<><span className="spinner"/>{busy==='compare'?'正在比较路线…':'正在查找地点…'}</>:'找到同城见面的中点 →'}</button>{error&&<div ref={feedback} className="inline-error" role="alert">{error}</div>}<p className="small muted">地点与路线查询由高德地图处理<br/>具体地点不会保存在浏览器</p></aside></div>
 {result&&<div className="local-results" aria-live="polite"><h2>{result.plans.length?'在这里，大家都近一点。':'暂时没有都能接受的地点。'}</h2><p className="muted">{result.disclaimer}</p>{result.plans.map((p,i)=><article className="local-result-card" key={p.place.id}><div className="local-result-head"><div><span className="kicker">{i===0?'最长用时最短':'另一个可行选择'}</span><h3>{p.place.name}</h3><p>{p.place.address}</p></div><strong>{p.maxMinutes}<small> 分钟<br/>最远的那个人</small></strong></div>{p.journeys.map(j=><div className="local-journey" key={j.name}><div><b>{j.name} · {j.origin.name}</b><p>{modes[j.mode as keyof typeof modes]} · {j.steps.join(' → ')||'详见地图路线'}</p></div><span>约 {j.minutes} 分钟{j.fareFen!==null&&<small>票价约 ¥{j.fareFen/100}</small>}</span></div>)}</article>)}{result.exclusions.length>0&&<ul className="local-exclusions">{result.exclusions.map((x,i)=><li key={i}>{x.place}：{x.reason}</li>)}</ul>}<p className="small muted">{result.source} · {new Date(result.queriedAt).toLocaleString('zh-CN')} 查询 · 仅比较本次候选，非全城最优。</p></div>}
 </section>;
}
